[package]

name = "concurrent-lru-cache"
version = "0.1.0"
edition = "2021"
description = "A concurrent LRU cache"
license = "MIT"

[dependencies]
linked-hash-map = "0.5.6"
concurrent-queue = "2.2.0"

[patch.crates-io]
linked-hash-map = { path = "linked-hash-map-0.5.6/" }
